## Aplicación de NumPy

-----------------------

#### Ejemplo 1

Los datos contenidos en el fichero [datos.txt](./datos.txt) describe las poblaciones de tres tipos de serpientes en el sur de Africa durante 20 años.

In [3]:
import numpy as np
data = np.loadtxt('./datos.txt')    # carga de los datos
data


array([[  2000.,  30000.,   3000.,  38300.],
       [  2001.,  37200.,   6100.,  48200.],
       [  2002.,  60200.,   9800.,  31600.],
       [  2003.,  77300.,  36200.,  38200.],
       [  2004.,  36300.,  69300.,  30600.],
       [  2005.,  20600.,  31700.,  49800.],
       [  2006.,  18100.,  19000.,  38600.],
       [  2007.,  21300.,  13000.,  32300.],
       [  2008.,  22000.,   8300.,  43600.],
       [  2009.,  26300.,   9100.,  32100.],
       [  2010.,  27100.,   7300.,  36000.],
       [  2011.,  30300.,   8000.,  36800.],
       [  2012.,  67000.,  12300.,  33800.],
       [  2013.,  76600.,  19600.,  30900.],
       [  2014.,  62300.,  36700.,  49300.],
       [  2015.,  19600.,  61100.,  39000.],
       [  2016.,  11200.,  29700.,  36700.],
       [  2017.,   7600.,  16800.,  41800.],
       [  2018.,  13600.,   9700.,  33300.],
       [  2019.,  16200.,  10100.,  31300.],
       [  2020.,  23700.,   8600.,  47300.]])

* Cálculo de la media de población de cada tipo a lo largo del tiempo.


In [4]:
data[: , 1:].mean()

30625.396825396827

In [5]:
d = data[:, 1:]

In [6]:
d.mean(axis = 0)

array([ 33547.61904762,  20257.14285714,  38071.42857143])

In [27]:
data[: , 2].mean()

20257.142857142859

In [28]:
data[: , 3].mean()

38071.428571428572

* Cálculo de la __desviación estándar__ de la muestra. Se trata de una medida de dispersión para variables. Muestra la agrupación de los datos alrededor de un valor central (la media o promedio).

In [7]:
d.std(axis = 0)

array([ 21173.55986102,  17581.93259404,   6209.91088481])

In [29]:
np.std(data)

19884.800629054753

In [30]:
np.std(data, 0)

array([  6.05530071e+00,   2.11735599e+04,   1.75819326e+04,
         6.20991088e+03])

* ¿Qué especie ha tenido más población por año?

In [17]:
maximo = d.max(axis = 1)

In [18]:
especie = d.argmax(axis = 1)

In [21]:
valores = list(zip(especie, maximo))

In [28]:
year = data[:, 0]

In [32]:
d = dict(zip(year,valores))

In [35]:
d2 = { int(c) : v for c, v in d.items()} # para referirse a todos los elementos del dicccionario hay que poner d.items

In [40]:
d2 = { int(c) : (e, int(m)) for c, (e, m) in d.items()} 
d2

{2000: (2, 38300),
 2001: (2, 48200),
 2002: (0, 60200),
 2003: (0, 77300),
 2004: (1, 69300),
 2005: (2, 49800),
 2006: (2, 38600),
 2007: (2, 32300),
 2008: (2, 43600),
 2009: (2, 32100),
 2010: (2, 36000),
 2011: (2, 36800),
 2012: (0, 67000),
 2013: (0, 76600),
 2014: (0, 62300),
 2015: (1, 61100),
 2016: (2, 36700),
 2017: (2, 41800),
 2018: (2, 33300),
 2019: (2, 31300),
 2020: (2, 47300)}

In [31]:
data[0][1:4].max()
for i in range(len(data)):
    print(data[i][1:4].max())

38300.0
48200.0
60200.0
77300.0
69300.0
49800.0
38600.0
32300.0
43600.0
32100.0
36000.0
36800.0
67000.0
76600.0
62300.0
61100.0
36700.0
41800.0
33300.0
31300.0
47300.0


In [54]:
raza=[]
data[0][1:4].max()
for i in range(len(data)):
    
    if data[i][1:4].max()==data[i][1]:
         raza.append(["especie 1",data[i][0]])
    if data[i][1:4].max()==data[i][2]:
         raza.append(["especie 2",data[i][0]])
    else : 
           raza.append(["especie 3",data[i][0]])
    
raza

[['especie 3', 2000.0],
 ['especie 3', 2001.0],
 ['especie 1', 2002.0],
 ['especie 3', 2002.0],
 ['especie 1', 2003.0],
 ['especie 3', 2003.0],
 ['especie 2', 2004.0],
 ['especie 3', 2005.0],
 ['especie 3', 2006.0],
 ['especie 3', 2007.0],
 ['especie 3', 2008.0],
 ['especie 3', 2009.0],
 ['especie 3', 2010.0],
 ['especie 3', 2011.0],
 ['especie 1', 2012.0],
 ['especie 3', 2012.0],
 ['especie 1', 2013.0],
 ['especie 3', 2013.0],
 ['especie 1', 2014.0],
 ['especie 3', 2014.0],
 ['especie 2', 2015.0],
 ['especie 3', 2016.0],
 ['especie 3', 2017.0],
 ['especie 3', 2018.0],
 ['especie 3', 2019.0],
 ['especie 3', 2020.0]]